GIT_HUB1='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'
GIT_HUB4='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'
GIT_HUB2='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'
GIT_HUB3='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'
